### ISSUE TITLE
Suggestions for the plugin: Add aliases and fix quality of life issues

### ISSUE THREAD

**Issue by DJIronic** [EncryptSL/LiteEco#10]
1.  Add aliases for commands:
`/pay` for `/money pay`
`/baltop` for `/money top`
`/bal `& `/balace` for `/money`

2. `/money <nick>` should work without say "target", there is no reasonf or having the target there

3. Players can send nearly 0 of currency:
![image](https://user-images.githubusercontent.com/9658012/200701588-58e92110-3e30-4281-b186-44a237432266.png)
Please limit the number of decimals behind . to be sent, or edit the formatting to show more of the balance sent to the nearest one.

**Comment by EncryptSL** [comment]
1. Aliasy jsem přidal odkaz na stažení testovací verze je v předchozím issue: #9 
2. Zde je trochu problém protože když jsem oddělal pryč money target <player>, vzniká tím problém když napíšu /money vypíše mi našeptávání sub příkazy a hráče dohromady. Tohle nejde řešit bohužel. Přidal jsem to ale moc se mi to nelíbí.
![image](https://user-images.githubusercontent.com/9441083/200737627-67ede9cf-5fce-4779-bbaf-dfb1a1e7530b.png)


4. Se mi nepotvrdil je jenom možné že jsem to zapomněl přidat v předchozí verzi.
![image](https://user-images.githubusercontent.com/9441083/200737322-09451d2c-9d92-4871-b6fe-229fee33f796.png)

Ani když bylo číslo 0.00 se mi to nepotvrdilo pokaždé to bylo zamítnuto.

**Comment by DJIronic** [comment]
1. Super

2. Toto nebude většinou problém, pokud pro možnost výpisu financní ostatních hráčů bude permise. Tím pádem nebudou běží hráčí vidět po `/money` seznam všech hráčů, jelikož nebudou mít permise na zobrazení jejich účtu. U admin teamu pak očekávám ,že příkazy bude znát a nebdue to takový problém.

3. Kolegovi se opakovaně dařilo mi posílat třeba 0.0000000000000001 (limit nul byl jen limit délky zprávy), plugin to logicky zaokrouhlil na nulu v rámci zprávy, ale čáska mi šla i opakovaně odeslat.

**Comment by EncryptSL** [comment]
Opraveno v následujícím buildu, ve verzi 1.1.5-SNAPSHOT na spigotu bude vše plně opraveno.

#9 Tato chyba byla také plně opravena, nemělo by se to už stávat nyní má /money top nebo dejme tomu /baltop stránkování,

Když zadáš /baltop nebo /money top <číslo> tak ti vyjede stránkování by default to nemusíš ani zadávat příkaz počítá s tím že chceš první stránku.

Kdyby si ještě něco našel neváhej napsat sorry za dlouhé čekání.

https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=479129 , oficiální updated zde.

**Comment by DJIronic** [comment]
Ahoj, nasadil jsem poslednív verzi ze spigotu a alias `/pay` pro `/money send` mi nefunguje. :/
![image](https://user-images.githubusercontent.com/9658012/202954278-dfa6c2b2-664c-49d6-92d2-57d197504626.png)
