### ISSUE TITLE
LiteEco + SuperLobby

### ISSUE THREAD

**Issue by PrograMysT** [EncryptSL/LiteEco#11]
Hello, i want to do a shop. My Lobby plugin runs this command when i buy an item in the shop - 'money remove %player_name% 10'
But it just pauses for a sec and then it spams this in the console.
at encryptsl.cekuj.net.api.AdaptiveEconomyProvider.getBalance(AdaptiveEconomyProvider.kt:69) ~[LiteEco.jar:?]

Thanks for your response.

![image_2022-11-17_213513792](https://user-images.githubusercontent.com/114109438/202554098-dcad9ca1-5020-4ceb-a162-2bd3dc85cadc.png)
![image_2022-11-17_213545182](https://user-images.githubusercontent.com/114109438/202554185-7a83f0b5-84fb-4550-8711-eb4184cc3672.png)

**Comment by EncryptSL** [comment]
Fixed by https://github.com/EncryptSL/LiteEco/commit/9794fa634fa10a90fae879bd7a2330ac76f9d101
Update is available on spigotmc.org page.

Link: https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/updates
