### ISSUE TITLE
Jiné pluginy mají problém komunikovat s Liteco

### ISSUE THREAD

**Issue by DJIronic** [EncryptSL/LiteEco#12]
Ahoj,

mám problém s pokusem nasadit plugin [PlayerAuctions](https://www.spigotmc.org/resources/%E2%AD%90-player-auctions-%E2%AD%90-%E2%9E%A2-let-your-players-sell-items-1-7-1-19.83073/).

při vytváření aukce se proletím na chybě v komunikaci s tvým pluginem: https://paste.brcb.eu/jimesetaby.less

Můžeš se na to prosím podívat? Also, když budeš mít chvilku, pracujeme na celkem cool projektu + mám firmu na webový aplikace, takže by bylo fajn si třeba napsat. :) Šimon DJ Čecháček#6803

Díky!

**Comment by DJIronic** [comment]
Also, looks like duplicate of https://github.com/EncryptSL/LiteEco/issues/11
Stáhnil jsem včera ten poslední file ze spigot a ten fix v tom commitu ohledně Superlobby tam očividně není :)

**Comment by EncryptSL** [comment]
Stáhl jsem aktuální přímo ze spigotu. 
Testováno na verzi 1.1.6-SNAPSHOT

Stáhni si prosím tuhle aktuální.
https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/download?version=475890

Tam je to opravné v této co používáš tahle chyba je.

**Comment by DJIronic** [comment]
![image](https://user-images.githubusercontent.com/9658012/203086425-a40d5920-91f0-45e2-93ec-a9b602695bd0.png)
Koukám, mám ten file na disku i na serveru :D tak nevím :D

**Comment by EncryptSL** [comment]
Jakou tam máš prosím Vault verzi.

**Comment by DJIronic** [comment]
Ahoj, no tu poslední :)

https://github.com/MilkBowl/Vault/releases/tag/1.7.3

Je z roku 2020.

**Comment by EncryptSL** [comment]
Po dalším zkoumání a otestování jak se SuperLobby tak i s PlayerAuctions pluginem.

Teď to neber nějak zle ale stává se to.
Jsem došel k závěru že buď, jsi zapomněl restartovat server nebo čistě náhodou jsi mohl provádět reload.

Plugin jako takovej funguje, chyba která se ukazovala je ve verzích 1.1.5 > a níže byla opravena v 1.1.6-SNAPSHOTU.

Chyba byla ta že pluginy se během kliknutí do GUI dotazovali na VaultAPI, metodu getBalance  která ovšem na mé straně předávala Null hodnotu protože je ozačena jako Deprecated, a tím pádem házela tuto chybu, 

V commitu https://github.com/EncryptSL/LiteEco/commit/9794fa634fa10a90fae879bd7a2330ac76f9d101, jsem udělal opravu tak že jsem původní volání této metody redirectl na tu kterou používá LiteEco.

Tohle je můj finální verdikt k této chybě kterou jsem opravil, dělá mi to celkem zmatek.

**Comment by DJIronic** [comment]
Ahoj,

mrzí mě, že jsem ti případně přidělal práci. Jsme sice přesvědčen, že jsem server restartoval a nic nenačítal za běhu, ale byla noc :)

Udělám druhé kolečko testů a znovu ověřím verze pluginů a dám vědět, jak to dopadlo.

Díky za tvůj čas při debugu.
