### ISSUE TITLE
Hey it's not a bug i just messed up.

### ISSUE THREAD

**Issue by Flowishloz** [EncryptSL/LiteEco#13]
### What happened?

I mass gave everyone 10000 by accident, now i want to remove that 10,000 from everyone, but there doesnt seem to be a way to do it. Any ideas how? i did /pay ** 10000.

### Plugin Version

1.1.7-SNAP

### You detected problem on this server platform ?

PaperMC

### Relevant log output

```shell
[12:35:04 INFO]: ohBreezY issued server command: /money remove ** 10000
```

**Comment by EncryptSL** [comment]
Hmm, this is a very confused for me, because i don't implemented global payment for all players, with ** this placeholder.

Now i go testing what really happened.

**Comment by Flowishloz** [comment]
Hey is there a command for mass money removal?

**Comment by EncryptSL** [comment]
In future release 1.1.9-SNAPSHOT i implement this feature.
