### ISSUE TITLE
Request for Edit

### ISSUE THREAD

**Issue by HestiiaSan** [EncryptSL/LiteEco#15]
### What happened?

Good day. I wanna change from the config´s something. I Try to change the colour from green to purple, so i use replace "<green" to "<purple" but the color not change. I get now the Word <purple> ahead the word. Can someone can help me ?
i write just one < bc, if u do both u dont see the word anymore~

### Plugin Version

1.19.2

### You detected problem on this server platform ?

PaperMC

**Comment by EncryptSL** [comment]
Hi i can give you smart tester for minimessages colors from paper.

<purple> is not valid color for minecraft. 

Minecraft have this colors: ```black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, or white```
Source: https://docs.adventure.kyori.net/minimessage/format.html

There you can testing colors https://webui.adventure.kyori.net/
