### ISSUE TITLE
[Bug]: Slow economy response? 

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#19]
### What happened?

Essentails keeps filling my console with "Slow economy response, took {0}ms"
This usually means the economy provider is slow when responding

I'm using MySQL what should i do?

### Plugin Version

LiteEco-1.1.8-SNAPSHOT

### You detected problem on this server platform ?

PurpurMC

**Comment by EncryptSL** [comment]
There is no related answer, Slow economy response can do more connections, on server, etc more open connections. Unoptimized database, more players using in sametime more transactions.

I can do something for optimization, i now implementing own API.

**Comment by LcyDev** [comment]
It's only on startup and apparently it's mostly caused when i put Slimefun (for some reason)

**Comment by EncryptSL** [comment]
Maybe fixed in version 1.2.0-SNAPSHOT https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=485549

**Comment by LcyDev** [comment]
Indeed, it was fixed!

**Comment by EncryptSL** [comment]
Okay, thanks for your response.
