### ISSUE TITLE
placeholders

### ISSUE THREAD

**Issue by FrinshHD** [EncryptSL/LiteEco#2]
The placeholders aren't working.

**Comment by EncryptSL** [comment]
Hi, without any additional info i can't help you.

Placeholders are available in version 1.1.0-SNAPSHOT.

I tested placeholders before update and works.

You can try send command /papi parse your_name %liteeco_balance% or %liteeco_balance_formatted%

If PAPI send error or something put error into pastebin.com

**Comment by EncryptSL** [comment]
Fixed in commit https://github.com/EncryptSL/LiteEco/commit/a876543b915706a33b91fb3dffaec0268969ba49

Please download updated version: https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=469759
