### ISSUE TITLE
[Question]: /money top = showing Null players, when Towny is installed.

### ISSUE THREAD

**Issue by ventus008** [EncryptSL/LiteEco#24]
### Your Question

I have question about top players list, some of it is showing null. Is there a way to remove it? I would appreciate all answers.

**Comment by LcyDev** [comment]
Yes, i had the same issue.
I'm working on a patch for this.

**Comment by LcyDev** [comment]
Would you like to remove them from the database or just to not show them in the baltop?

**Comment by EncryptSL** [comment]
Please post your version in 1.2.1-SNAPSHOT, balance top working for me.

![image](https://user-images.githubusercontent.com/9441083/212555748-02a114fd-9f6b-43f5-a2d5-4c27577c7abe.png)

**Comment by EncryptSL** [comment]
Or update to 1.2.1-SNAPSHOT

**Comment by LcyDev** [comment]
In my case, i deleted Essentials/playerdata (Towns included), this caused towny to generate new uuids for the towns.

After that, null accounts appeared in the baltop
![image](https://user-images.githubusercontent.com/72966048/212556903-dcabbf72-9eae-4134-87cc-9b60b2d00c5b.png)

I'm making a command to set player names in the MySQL database, so i can know what accounts are null, save them, delete them and manually send money to the respected Town

**Comment by LcyDev** [comment]
![image](https://user-images.githubusercontent.com/72966048/212558187-6afba636-68ff-4197-bbf6-79ec6b21259a.png)
Nice.

**Comment by EncryptSL** [comment]
I can say only i this confirm with towny.

**Comment by EncryptSL** [comment]
Issue with null player name is because towny using npc fake accounts.

And LiteEco don't know what is fake account.

**Comment by LcyDev** [comment]
I made a command to remove null players but the implementation is not elegant (Iterating over HashMap obtained from Baltop)

Do you think this command could be a feature?

**Comment by ventus008** [comment]
Hello, Thank you for your responses.

So the "null" players is being generated by towny? And in order to remove them from showing in Baltop is to access databese.db?

**Comment by EncryptSL** [comment]
> I made a command to remove null players but the implementation is not elegant (Iterating over HashMap obtained from Baltop)
> 
> Do you think this command could be a feature?

I'm not sure if this is a possible way, because everytime towny generating accounts. 
Can be implemented something like  /money|balance|bal purge [argument] something like nullaccounts, or /money purge. Only for feature like a tool when something broke.

Towny must be blocked for now,



> Hello, Thank you for your responses.
> 
> So the "null" players is being generated by towny? And in order to remove them from showing in Baltop is to access databese.db?

In this, case you don't have tools how delete null accounts because database.db can't be opened with programs.
I next update can be implemented tool how null accounts delete.

**Comment by LcyDev** [comment]
The thing is, towns SHOULD have names, normally they aren't null and are something like `town-Bonn`

**Comment by EncryptSL** [comment]
But i think there is not another necessary, add another functions. But Imho, idk.

**Comment by LcyDev** [comment]
I see now.

**Comment by EncryptSL** [comment]
Plugin Towny is not supported for now, maybe in future...
