### ISSUE TITLE
[Bug]: Null accounts in placeholders

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#35]
### What happened?

![image](https://user-images.githubusercontent.com/72966048/215377659-b12ac413-5265-4cd9-a958-a8b1ab3cd7db.png)

Parsed through `%liteeco_top_player_<1-7>%`
![image](https://user-images.githubusercontent.com/72966048/215377763-66d5e257-f3f2-4abf-af19-3c84c16899e7.png)

### Plugin Version

1.2.4-SNAPSHOT

### You detected problem on this server platform ?

PaperMC, PurpurMC

**Comment by EncryptSL** [comment]
Hi, can you please send your database file or exported table from phpmyadmin if you are using plugin on production.

Now i can't this reproduce.

**Comment by LcyDev** [comment]
https://www.mediafire.com/file/u5ufr53hkus9riw/database.db/file
