### ISSUE TITLE
[Bug]: Stacktrace when incomplete placeholder

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#36]
### What happened?

When parsing `%liteeco_top_player_%` or `%liteeco_top_player_<alpha>%` this error will show.

I expect it to return null or something else, like other placeholders do.

### Plugin Version

1.2.4-SNAPSHOT

### You detected problem on this server platform ?

PaperMC, PurpurMC

### Relevant log output

```shell
https://paste.gg/p/ConaII_/89fe8540dffe4dedb2b4a18d89dd420f
```

**Comment by EncryptSL** [comment]
Fixed

**Comment by LcyDev** [comment]
Not fixed yet.
