### ISSUE TITLE
pay command pay what ever you want

### ISSUE THREAD

**Issue by iPain3G** [EncryptSL/LiteEco#4]
When you use the plugin on an Paper 1.19.2 server you can pay more money to another player as you currently have in your wallet.

I had to disable the pay feature.

Plugin version: 1.1.1
Paper version: 120
Vault version: 1.7.3

**Comment by EncryptSL** [comment]
Fixed in commit https://github.com/EncryptSL/LiteEco/commit/a876543b915706a33b91fb3dffaec0268969ba49

Please download updated version: https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=469759
