### ISSUE TITLE
[Feature Request] [Question]:  Colors

### ISSUE THREAD

**Issue by ItzSvefil** [EncryptSL/LiteEco#41]
### Your Question

Ahoj, všiml jsem si, že jsi čech. Takže budu psát česky.

Chtěl jsem se zeptat, jestli by nebyla možnost v budoucnu hex barev. (zjistil jsem že to jde xd) 
Taktéž mě zajímá jaké všechny barvy se dají použít. protože např. <gray> je světle šedá, ve hře ale tmavě. (taky jsem si to mezitím našel sám)
Ale stejně mám problém, řeším <bold> ale nemůžu za každou cenu nikde najít, jak to z boldu udělám opět na normální písmo.

Taktéž bych se chtěl zeptat, jestli máš nějaký komunitní dc. Vždy se hodí nějaký kontakt na nové lidi v tomto oboru. 😄 
Děkuji za odpověď. Svefil

**Comment by EncryptSL** [comment]
Spektrum barev i hex barvy jsou povolené, je to připnuto v tomto issue https://github.com/EncryptSL/LiteEco/issues/18.

Více informací najdeš právě v již zmíněném issue.

Co se týká komunitního discordu, nevedu žádný z hlediska administrativy, mimo jiné zatím to neplánuji ale možná že v nějaké době by to mohlo být možné.

Pokud by si měl další otázky nechám tohle issue otevřené.

**Comment by ItzSvefil** [comment]
Děkuju za pomoc, omlouvám se za blbou otázku. Můžeš to zavřít.
