### ISSUE TITLE
[Feature Request]: add comand and more

### ISSUE THREAD

**Issue by Zarkness** [EncryptSL/LiteEco#47]
Add /paytoggle command, so that users can toggle whether they receive payments from other users or not, add a placeholder to detect if they have active payments or not.

add the possibility that the /baltop and the baltop placeholders show the money that all the users that enter the server have.

for example if the baltop today shows 100 people because it was the maximum number of users that entered the server during 3 months, if in the following months/days more people enter the baltop it will show the money of all users.

to be able to put in the baltop and in placeholders that instead of 30.00 it shows 30, 1000... or 1k, 10k, 10M instead of 1.00k for the decimals.

add a placeholder where neither the name nor the prefix of the economy is shown and the same for the /baltop and its placeholders, the same for the other options since I don't want the name nor the prefix of the economy to be shown.

add the possibility to use the legacy colors apart from the minimessage ones.

If there is something that is not understood, I would appreciate if you tell me what part is not understood to try to explain it better.

**Comment by Zarkness** [comment]
hi @EncryptSL ?

**Comment by EncryptSL** [comment]
Hi, sorry for late answer. I have personal live and i can't sometimes spent time on free projects.

1. Paytoggle is possible
2. If i understand, you mean count all money and add into placeholder, this is too posible. ? Or add into baltop all users.
3. Can be posible but there must be changed formatting.
4. There is only one solution, i think but, i don't remember if this is in code, but in config you can remove prefix of currency and name of currency. I mean set to empty. 
5. Myself i think no, i don't have plan for supporting legacy colors.

If someone from others developers have any idea, can implement this myselfs, and send PR.

I have only time for give support of stable builds and high bug fixes.

**Comment by EncryptSL** [comment]
But i use somethink from your idea.

**Comment by Zarkness** [comment]
- 2 What I mean is that the /baltop and placeholders %liteeco_top_player_<number>% || %liteeco_top_balance_<number>% || %liteeco_top_formatted_<number>% the maximum is not 10 as it is now, but it shows you from top 1 to infinity, with infinity I mean until the maximum of users that have entered to date, and shows you in the position that each user is together with their money.

- 3 Ok and it would be possible to add it soon? I would like to be able to put the economy without decimals and also to be able to put that in the scoreboard see 1M instead of 1000000.

 - 4 Ok, so in order not to show neither the name nor the prefix, I will do that.
 
 and to the rest no problem, the legacy colors is more for personal taste, the paytoggle if it is possible to add it soon I would be grateful.
