### ISSUE TITLE
no second place

### ISSUE THREAD

**Issue by REDKING-11** [EncryptSL/LiteEco#5]
![2022-08-26_17 56 49](https://user-images.githubusercontent.com/99126547/186933880-eaf4e7e1-2ae8-4028-b2ad-e78300d6c1ee.png)

location: world:-109,465:74,000:-66,420
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
pages:
- lines:
  - content: Balance
    height: 0.3
  - content: '&6#1 &2%liteeco_top_player_1% &a=&6%liteeco_top_formatted_1%'
    height: 0.3
  - content: '&6#2 &2%liteeco_top_player_2% &a=&6%liteeco_top_formatted_2%'
    height: 0.3
  - content: '&6#3 &2%liteeco_top_player_3% &a=&6%liteeco_top_formatted_3%'
    height: 0.3
  - content: '&6#4 &2%liteeco_top_player_4% &a=&6%liteeco_top_formatted_4%'
    height: 0.3
  - content: '&6#5 &2%liteeco_top_player_5% &a=&6%liteeco_top_formatted_5%'
    height: 0.3
  - content: '&6#6 &2%liteeco_top_player_6% &a=&6%liteeco_top_formatted_6%'
    height: 0.3
  - content: '&6#7 &2%liteeco_top_player_7% &a=&6%liteeco_top_formatted_7%'
    height: 0.3
  - content: '&6#8 &2%liteeco_top_player_8% &a=&6%liteeco_top_formatted_8%'
    height: 0.3
  - content: '&6#9 &2%liteeco_top_player_9% &a=&6%liteeco_top_formatted_9%'
    height: 0.3
  - content: '&6#10 &2%liteeco_top_player_10% &a=&6%liteeco_top_formatted_10%'
    height: 0.3
  actions: {}

**Comment by REDKING-11** [comment]
and i use decent holograms

**Comment by EncryptSL** [comment]
Please send info about version of plugin thanks.

**Comment by EncryptSL** [comment]
In last version this bug was fixed.

**Comment by REDKING-11** [comment]
thx
