### ISSUE TITLE
[SideClient/Bug]: Commands not working in moded client probably !?

### ISSUE THREAD

**Issue by Vlkos77** [EncryptSL/LiteEco#51]
### What happened?

No commands work. Using placeholders and vault i can see my balance, but when i do /bal for example, or any other command of this plugin, nothing happens. it appears on console, but no output. Also, if I add myself money using commands, nothing adds (i checked using placeholders)

### Plugin Version

1.3.4-SNAPSHOT and 1.3.3-SNAPSHOT

### You detected problem on this server platform ?

PaperMC

**Comment by EncryptSL** [comment]
Everything works
- Tested in console
- Tested in game

Tips for new users using LiteEco
- You must have for working commands, plugin PermissionsEx or from LuckPerms.
- Why because IncendoCloud not supporting setted permissions from plugin.yml from LiteEco.

![image](https://github.com/EncryptSL/LiteEco/assets/9441083/559792b1-7b65-4284-88bd-08f4ce1237e0)
![image](https://github.com/EncryptSL/LiteEco/assets/9441083/e7a7030a-666c-4b66-a38d-137d8e18c49a)

**Comment by Vlkos77** [comment]
What? I still have the same issue...


https://github.com/EncryptSL/LiteEco/assets/81807983/4ef323cd-8cde-4704-b5a7-71cbc9965aac

**Comment by EncryptSL** [comment]
Pošli sem vypis pluginů.
Může se stát že někdy se pluginy mezi sebou navzájem kříží a využívají třeba stejné funkce a proto nefungují příkazy.

Full log z konzole ze startu serveru.
Nejlépe uděláš když log hodíš sem [pastes.dev](https://pastes.dev/)

**Comment by Vlkos77** [comment]
Pluginy: https://pastes.dev/cIs2bmFWvP
Konzole: https://pastes.dev/rdbFoUOYdr

**Comment by Vlkos77** [comment]
Ok, sice mi přijde divný, že by příkazy na featheru nefungovatly a na klasickém launcheru ano, zkusím to, akorát mi teď nejede server (změna hostingu)

zítra už by měl server normálně běžet, takže se na to podívám

**Comment by EncryptSL** [comment]
Je to poněkud divné ale parkrát jsem se s tím setkal.

Moje vyhodnocení na závěr plugin funguje z logu jsem nic nevyčetl všechno se zdá být v pořádku, pluginy se zdají být nekonfliktní a co se týká mého pluginu nemůžu to označit za chybu. 

Problém nedokážu replikovat čili z mé strany je to zatím všechno.
Pokud na nic nepříjdeš, jel bych starou metodou odstraňování pluginů jeden po druhém.

**Comment by Vlkos77** [comment]
Ok, zkusil jsem to z normálního clientu. Nyn už se v konzoli ukazuje, že jsem command odeslal, nicméně stále žádná odpověď od pluginu.

**Comment by Vlkos77** [comment]
Ale to nevadí, nakonec jsem se rozhodl z serveru udělat čistou vanillu jen s qol pluginy, takže asi ekonomiku nakonec přidávat nebudu. ale někdy do budoucna bych tento skvélý plugin určitě využil, tedy až mi začne fungovat :D

**Comment by EncryptSL** [comment]
Jasně, já jenom z mého hlediska bug to není protože kdyby byl nefungovalo by to jiným nebo by se to potvrdilo přímo u mě už při vývoji. Může se stát že někdy nějaký plugin prostě ten druhej rozbije.
