### ISSUE TITLE
[Bug]: Sync breaks on Bungeecord(Waterfall)

### ISSUE THREAD

**Issue by BijuuKrunos** [EncryptSL/LiteEco#70]
### What happened?

I have an Bungeecord Network where on each Server Liteeco is installed and connected to 1 mysql Server. I tested a lot and often it just dont refresh from or to the database if i change the Server, but everytime in the log it says that it does it. 
Is the Plugin not suited for Bungeecord and i am just using it wrong or is there something broken?
Often by login its pulling the wrong old number even if the database is updated.

### Plugin Version

1.4.1-Snapshot

### You detected problem on this server platform ?

PaperMC

### Version /version - output

```shell
This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)

waterfall-536.jar
```

### Relevant log output

```shell
log seems to be ok.
```

**Comment by BijuuKrunos** [comment]
My plugin config, identical on all Servers:
# Official settings for this plugin.
plugin:
  # Translations list of supported locales below
  # https://github.com/EncryptSL/LiteEco/blob/main/src/main/kotlin/encryptsl/cekuj/net/api/enums/LangKey.kt
  translation: EN_US
  # Plugin prefix
  prefix: ''
  # Debugging
  debug: true

economy:
  currency_prefix: ''
  # Name of Currency
  currency_name: ''
  # This amount is granted to players who don't have an existing account in the database.
  starting_balance: 0
  # Convert large currency values into a more compact format.
  compact_display: false

formatting:
  # Currency value format
  currency_pattern: '#,##0.00'
  # Compact value format
  compacted_pattern: '#,##0.0##'
  # Locale symbol format
  currency_locale: de-DE

# These settings toggle messages.
messages:
  global:
    notify_add: true
    notify_withdraw: true
    notify_set: true
  target:
    notify_add: true
    notify_withdraw: true
    notify_set: true

# Settings for Database or SQLite connection.
database:
  # For SQLite, the path to the SQLite database file: jdbc:sqlite:plugins/LiteEco/database.db
  # For MySQL, the JDBC connection URL in the format: jdbc:mysql://your_host:port/name_of_database
  connection:
    # Settings for JDBC_HOST
    jdbc_url: jdbc:mysql://localhost:3306/BLANK
    # The username of the user to connect to your database (MySQL only).
    username: BLANK
    # The password of the user to connect to your database (MySQL only).
    password: BLANK

# Please don't remove this version settings
version: 1.2.1

**Comment by BijuuKrunos** [comment]
After testing some more i am sure, that it is a sync problem. The time where i am switching the Server is too fast and the plugin dont get to update the database fast enough.

**Comment by BijuuKrunos** [comment]
ahh ok my bad it semms that this plugin is not bungee compatible. Would be nice to mention that in the spigot page so that not another one is trying it for that. It was a great Plugin cry xD

**Comment by EncryptSL** [comment]
Plugin don't have support for proxy server.
I added notify on the page, plugin don't have support for proxy.

Now i don't have time for planning other updates, because this is a free time project.
If for bungeecord support, will be huge request. I guarantee adding this feature.
