### ISSUE TITLE
[Feature Request]: beign able to remove currency name and currency prefix

### ISSUE THREAD

**Issue by iRazvan2745** [EncryptSL/LiteEco#71]
### Your ideas

I have something new for plugin !

**Comment by EncryptSL** [comment]
You can set empty
economy:
  # Prefix of Currency
  currency_prefix: '' <- Set Empty String
  # Name of Currency
  currency_name: '' <- Set Empty String
  # This amount is granted to players who don't have an existing account in the database.
  starting_balance: 0
  # Convert large currency values into a more compact format.
  compact_display: true
