### ISSUE TITLE
[Feature Request]: EssenitalsX converter since /vault-convert doesnt work with liteeco

### ISSUE THREAD

**Issue by iRazvan2745** [EncryptSL/LiteEco#74]
### Your ideas

I have something new for plugin !

**Comment by EncryptSL** [comment]
I try something cook.

**Comment by EncryptSL** [comment]
Support for Convert was added, in next release.

https://github.com/EncryptSL/LiteEco/commit/5c0968541900984a2d3554983a310054083086e3#diff-5f010ffd81340a387c7f7cc5dc53443975f03b16bd02df7b0aed5677bc410f1fR211-R235
