### ISSUE TITLE
[Bug]: baltop not updating

### ISSUE THREAD

**Issue by alec-jensen** [EncryptSL/LiteEco#77]
### What happened?

the baltop command seems to be stuck in time.

### Plugin Version

1.4.3-SNAPSHOT

### You detected problem on this server platform ?

PurpurMC

### Version /version - output

```shell
[21:50:28 INFO]: Current: git-Purpur-2155 (MC: 1.20.4)*
Previous: git-Purpur-2153 (MC: 1.20.4)
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### Relevant log output

```shell
there are no relevant logs
```

**Comment by EncryptSL** [comment]
Your issue is a not a bug, Baltop is updated while player leave server, because all players who join server have data in memory cache. Baltop is returned from database not from cache for this reason yo can see older data.

**Comment by alec-jensen** [comment]
Could this functionality be changed then where it also grabs data from the cache?

**Comment by EncryptSL** [comment]
I can try something. Do with this.

**Comment by EncryptSL** [comment]
Implemented feature to updating bal top.
In this release: https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-20.101934/update?update=537541
