### ISSUE TITLE
[Feature Request]: logging all transactions

### ISSUE THREAD

**Issue by alec-jensen** [EncryptSL/LiteEco#78]
### Type of function to add or improvement

Others

### Your ideas

logging transactions could be useful in cases where the database corrupts etc

**Comment by EncryptSL** [comment]
I don't know if this is a possible, but i implemented simple logger for sql transactions..

In this release: https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-20.101934/update?update=537541

**Comment by alec-jensen** [comment]
I meant more of something that AuctionHouse and EconomyShopGUI have, where all transactions are appended to a file

**Comment by EncryptSL** [comment]
Feature of logging economy transaction is implemented into plugin in version 1.4.5.
