### ISSUE TITLE
messages 

### ISSUE THREAD

**Issue by shiref11** [EncryptSL/LiteEco#8]
hi anyway to git rid of this message like a disable option ??
![Screenshot_2022-10-08-15-19-14-012_net kdt pojavlaunch](https://user-images.githubusercontent.com/91873517/194709630-62d85891-d5e4-47d5-81da-2306ee21b4f1.jpg)

**Comment by EncryptSL** [comment]
Probably in next build.

**Comment by shiref11** [comment]
plz make it as fast as u can

**Comment by EncryptSL** [comment]
Updated, https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=475752

Recommended way for installation of this update is stop server and remove old [config.yml](https://github.com/EncryptSL/LiteEco/tree/main/.docs#setup) or manual copy new config.

**Comment by EncryptSL** [comment]
Closed with commit https://github.com/EncryptSL/LiteEco/commit/7ccb28a681535c854fa8e68b542d04ba51521f32
