### ISSUE TITLE
/money top command does not work properly

### ISSUE THREAD

**Issue by DJIronic** [EncryptSL/LiteEco#9]
Command `/money top` is not reporting the top players in the game.

This is how the comand result looks:
![image](https://user-images.githubusercontent.com/9658012/200698903-3aa250e2-97c8-4acf-840e-0fb6874ad4b3.png)

But when I look in the DB, there are players with 100 000+ in the currency, so they should be up on the top:
![image](https://user-images.githubusercontent.com/9658012/200699108-70e18e50-6162-4021-971b-b4a74f83370a.png)

We also tried to remove all the money of players and set only few of us a balance to see, if the plugin will work it out with smaller numbers, but that not helped. As you can see, names in the baltop are repeating, but with zero balance.

![image](https://user-images.githubusercontent.com/9658012/200699240-2110d0fa-489f-4f94-8fb3-e6ef533d6f3d.png)

and here is the DB with two of us having money:
![image](https://user-images.githubusercontent.com/9658012/200699280-db1d2e6d-4d6c-487f-8eaf-ec0bad3e52dc.png)

**Also placeholder for the top player, top balance are not working, it will show the wrong numbers, the same listed in money top command.**

We would love to see this fixed.

PS: Můžeme komunikovat i česky :)

**Comment by EncryptSL** [comment]
Po pravdě, chyba by někde mohla být neříkám že ne. 
Testováním chyb jsem ale neodhalil příčinu co popisuješ. 

Testování jsem provedl s čistou tabulkou a databází v SQL modu.

S výpisem okolo 20 účtů, při čemž jsem každému z nich přidělil random hodnoty.
Výsledek řazení ale ukázal že by mělo fungovat, 
![image](https://user-images.githubusercontent.com/9441083/200722482-2ee43291-796d-4119-9602-9f5ea68c4319.png)

Pokusím se tohle chování ještě otestovat přímo ve hře, případně ho nějak opravit.

**Comment by EncryptSL** [comment]
Doplnujicí otázka používáš doufám verzi 1.1.4-SNAPSHOT.

**Comment by EncryptSL** [comment]
Podařilo se mi problém replikovat až jsem nahodil tuhle verzi - 1.1.4-SNAPSHOT
Při téhle vývojové verzi se mi tohle nestalo, https://drive.google.com/file/d/1BC-ad5o9jjtU_UTDpMHaUO2KEI0Jc9CL/view

Můžeš tohle potvrdit. Případně dej vědět.

**Comment by DJIronic** [comment]
Nahodím a vyzkouším

**Comment by EncryptSL** [comment]
Opraveno zmíněno v #10
